name: Regression Tests

on:
  push:
    branches: [ "main" ]

jobs:  
  web_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node 16
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Preparation
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb ca-certificates net-tools netcat-openbsd gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2t64


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Init Browser Library
      run: rfbrowser init

    - name: Run Web Tests in Parallel
      run: |
        chmod +x run_all_tests.sh
        ./run_all_tests.sh

    - name: Upload Robot Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: reports/merged

    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      if: always()
      with:
        name: Web Test Results
        path: reports/merged/merged_output.xml
        reporter: java-junit
